<?php

namespace App\Models;

use App\Http\Controllers\API\BaseController;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class Product extends Model
{
    use HasFactory;

    protected $fillable = ['name','description','price','quantity','category_id'];

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($product){
            $product->externalID=Str::random(30);
        });
    }

}
